{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## IMPORTS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/bin/bash: line 1: conda: command not found\n",
      "Requirement already satisfied: langchain==0.3.15 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (0.3.15)\n",
      "Requirement already satisfied: transformers==4.48.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (4.48.1)\n",
      "Requirement already satisfied: torch==2.5.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (2.5.1)\n",
      "Requirement already satisfied: langchain-community==0.3.15 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (0.3.15)\n",
      "Requirement already satisfied: langchain-experimental==0.3.4 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.3.4)\n",
      "Requirement already satisfied: pandas==2.2.3 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (2.2.3)\n",
      "Requirement already satisfied: langchain-huggingface==0.1.2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.1.2)\n",
      "Requirement already satisfied: pydantic==2.10.5 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (2.10.5)\n",
      "Requirement already satisfied: accelerate==1.3.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (1.3.0)\n",
      "Requirement already satisfied: llama-cpp-python==0.3.6 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (0.3.6)\n",
      "Requirement already satisfied: PyYAML>=5.3 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (6.0.2)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (2.0.37)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (3.11.11)\n",
      "Requirement already satisfied: langchain-core<0.4.0,>=0.3.31 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (0.3.31)\n",
      "Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.3 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (0.3.5)\n",
      "Requirement already satisfied: langsmith<0.4,>=0.1.17 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (0.3.1)\n",
      "Requirement already satisfied: numpy<2,>=1.22.4 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (1.26.4)\n",
      "Requirement already satisfied: requests<3,>=2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (2.32.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain==0.3.15->-r requirements.txt (line 1)) (9.0.0)\n",
      "Requirement already satisfied: filelock in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (3.17.0)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (0.27.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (24.2)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (2024.11.6)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (0.21.0)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (0.5.2)\n",
      "Requirement already satisfied: tqdm>=4.27 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from transformers==4.48.1->-r requirements.txt (line 2)) (4.67.1)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (4.12.2)\n",
      "Requirement already satisfied: networkx in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (3.4.2)\n",
      "Requirement already satisfied: jinja2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (3.1.5)\n",
      "Requirement already satisfied: fsspec in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (2024.12.0)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.127)\n",
      "Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (9.1.0.70)\n",
      "Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.5.8)\n",
      "Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (11.2.1.3)\n",
      "Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (10.3.5.147)\n",
      "Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (11.6.1.9)\n",
      "Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.3.1.170)\n",
      "Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (2.21.5)\n",
      "Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.127)\n",
      "Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (12.4.127)\n",
      "Requirement already satisfied: triton==3.1.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (3.1.0)\n",
      "Requirement already satisfied: sympy==1.13.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from torch==2.5.1->-r requirements.txt (line 3)) (1.13.1)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain-community==0.3.15->-r requirements.txt (line 4)) (0.6.7)\n",
      "Requirement already satisfied: httpx-sse<0.5.0,>=0.4.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain-community==0.3.15->-r requirements.txt (line 4)) (0.4.0)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain-community==0.3.15->-r requirements.txt (line 4)) (2.7.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2024.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pandas==2.2.3->-r requirements.txt (line 6)) (2025.1)\n",
      "Requirement already satisfied: sentence-transformers>=2.6.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (3.3.1)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pydantic==2.10.5->-r requirements.txt (line 8)) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.27.2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pydantic==2.10.5->-r requirements.txt (line 8)) (2.27.2)\n",
      "Requirement already satisfied: psutil in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from accelerate==1.3.0->-r requirements.txt (line 9)) (6.1.1)\n",
      "Requirement already satisfied: diskcache>=5.6.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from llama-cpp-python==0.3.6->-r requirements.txt (line 10)) (5.6.3)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from sympy==1.13.1->torch==2.5.1->-r requirements.txt (line 3)) (1.3.0)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (2.4.4)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (1.3.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (24.3.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (1.5.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (6.1.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (0.2.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.15->-r requirements.txt (line 1)) (1.18.3)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community==0.3.15->-r requirements.txt (line 4)) (3.25.1)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain-community==0.3.15->-r requirements.txt (line 4)) (0.9.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from jinja2->torch==2.5.1->-r requirements.txt (line 3)) (3.0.2)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langchain-core<0.4.0,>=0.3.31->langchain==0.3.15->-r requirements.txt (line 1)) (1.33)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (0.28.1)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (3.10.15)\n",
      "Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (1.0.0)\n",
      "Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (0.23.0)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain-community==0.3.15->-r requirements.txt (line 4)) (1.0.1)\n",
      "Requirement already satisfied: six>=1.5 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 6)) (1.17.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.3.15->-r requirements.txt (line 1)) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.3.15->-r requirements.txt (line 1)) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.3.15->-r requirements.txt (line 1)) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from requests<3,>=2->langchain==0.3.15->-r requirements.txt (line 1)) (2024.12.14)\n",
      "Requirement already satisfied: scikit-learn in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from sentence-transformers>=2.6.0->langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (1.6.1)\n",
      "Requirement already satisfied: scipy in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from sentence-transformers>=2.6.0->langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (1.15.1)\n",
      "Requirement already satisfied: Pillow in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from sentence-transformers>=2.6.0->langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (11.1.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from SQLAlchemy<3,>=1.4->langchain==0.3.15->-r requirements.txt (line 1)) (3.1.1)\n",
      "Requirement already satisfied: anyio in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (4.8.0)\n",
      "Requirement already satisfied: httpcore==1.* in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (1.0.7)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (0.14.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.31->langchain==0.3.15->-r requirements.txt (line 1)) (3.0.0)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain-community==0.3.15->-r requirements.txt (line 4)) (1.0.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from scikit-learn->sentence-transformers>=2.6.0->langchain-huggingface==0.1.2->-r requirements.txt (line 7)) (3.5.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.4,>=0.1.17->langchain==0.3.15->-r requirements.txt (line 1)) (1.3.1)\n",
      "Package                  Version\n",
      "------------------------ -----------\n",
      "accelerate               1.3.0\n",
      "aiohappyeyeballs         2.4.4\n",
      "aiohttp                  3.11.11\n",
      "aiosignal                1.3.2\n",
      "annotated-types          0.7.0\n",
      "anyio                    4.8.0\n",
      "asttokens                3.0.0\n",
      "attrs                    24.3.0\n",
      "certifi                  2024.12.14\n",
      "charset-normalizer       3.4.1\n",
      "comm                     0.2.2\n",
      "dataclasses-json         0.6.7\n",
      "debugpy                  1.8.12\n",
      "decorator                5.1.1\n",
      "diskcache                5.6.3\n",
      "executing                2.2.0\n",
      "filelock                 3.17.0\n",
      "frozenlist               1.5.0\n",
      "fsspec                   2024.12.0\n",
      "greenlet                 3.1.1\n",
      "h11                      0.14.0\n",
      "httpcore                 1.0.7\n",
      "httpx                    0.28.1\n",
      "httpx-sse                0.4.0\n",
      "huggingface-hub          0.27.1\n",
      "idna                     3.10\n",
      "ipykernel                6.29.5\n",
      "ipython                  8.31.0\n",
      "jedi                     0.19.2\n",
      "Jinja2                   3.1.5\n",
      "joblib                   1.4.2\n",
      "jsonpatch                1.33\n",
      "jsonpointer              3.0.0\n",
      "jupyter_client           8.6.3\n",
      "jupyter_core             5.7.2\n",
      "langchain                0.3.15\n",
      "langchain-community      0.3.15\n",
      "langchain-core           0.3.31\n",
      "langchain-experimental   0.3.4\n",
      "langchain-huggingface    0.1.2\n",
      "langchain-text-splitters 0.3.5\n",
      "langsmith                0.3.1\n",
      "llama_cpp_python         0.3.6\n",
      "MarkupSafe               3.0.2\n",
      "marshmallow              3.25.1\n",
      "matplotlib-inline        0.1.7\n",
      "mpmath                   1.3.0\n",
      "multidict                6.1.0\n",
      "mypy-extensions          1.0.0\n",
      "nest-asyncio             1.6.0\n",
      "networkx                 3.4.2\n",
      "numpy                    1.26.4\n",
      "nvidia-cublas-cu12       12.4.5.8\n",
      "nvidia-cuda-cupti-cu12   12.4.127\n",
      "nvidia-cuda-nvrtc-cu12   12.4.127\n",
      "nvidia-cuda-runtime-cu12 12.4.127\n",
      "nvidia-cudnn-cu12        9.1.0.70\n",
      "nvidia-cufft-cu12        11.2.1.3\n",
      "nvidia-curand-cu12       10.3.5.147\n",
      "nvidia-cusolver-cu12     11.6.1.9\n",
      "nvidia-cusparse-cu12     12.3.1.170\n",
      "nvidia-nccl-cu12         2.21.5\n",
      "nvidia-nvjitlink-cu12    12.4.127\n",
      "nvidia-nvtx-cu12         12.4.127\n",
      "orjson                   3.10.15\n",
      "packaging                24.2\n",
      "pandas                   2.2.3\n",
      "parso                    0.8.4\n",
      "pexpect                  4.9.0\n",
      "pillow                   11.1.0\n",
      "pip                      24.3.1\n",
      "platformdirs             4.3.6\n",
      "prompt_toolkit           3.0.50\n",
      "propcache                0.2.1\n",
      "psutil                   6.1.1\n",
      "ptyprocess               0.7.0\n",
      "pure_eval                0.2.3\n",
      "pydantic                 2.10.5\n",
      "pydantic_core            2.27.2\n",
      "pydantic-settings        2.7.1\n",
      "Pygments                 2.19.1\n",
      "python-dateutil          2.9.0.post0\n",
      "python-dotenv            1.0.1\n",
      "pytz                     2024.2\n",
      "PyYAML                   6.0.2\n",
      "pyzmq                    26.2.0\n",
      "regex                    2024.11.6\n",
      "requests                 2.32.3\n",
      "requests-toolbelt        1.0.0\n",
      "safetensors              0.5.2\n",
      "scikit-learn             1.6.1\n",
      "scipy                    1.15.1\n",
      "sentence-transformers    3.3.1\n",
      "setuptools               75.8.0\n",
      "six                      1.17.0\n",
      "sniffio                  1.3.1\n",
      "SQLAlchemy               2.0.37\n",
      "stack-data               0.6.3\n",
      "sympy                    1.13.1\n",
      "tenacity                 9.0.0\n",
      "threadpoolctl            3.5.0\n",
      "tokenizers               0.21.0\n",
      "torch                    2.5.1\n",
      "tornado                  6.4.2\n",
      "tqdm                     4.67.1\n",
      "traitlets                5.14.3\n",
      "transformers             4.48.1\n",
      "triton                   3.1.0\n",
      "typing_extensions        4.12.2\n",
      "typing-inspect           0.9.0\n",
      "tzdata                   2025.1\n",
      "urllib3                  2.3.0\n",
      "wcwidth                  0.2.13\n",
      "wheel                    0.45.1\n",
      "yarl                     1.18.3\n",
      "zstandard                0.23.0\n"
     ]
    }
   ],
   "source": [
    "! conda activate myprojects\n",
    "! pip install -r requirements.txt\n",
    "! pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import main"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## USAGE"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "TO RUN Benchmarking tests against a pre-defined set of questions and sets of pre-defined configurations on the LLM"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/bot/personal_proj/moneylion-ml-assessment/main.py:57: LangChainDeprecationWarning: Importing SQLDatabase from langchain is deprecated. Please replace deprecated imports:\n",
      "\n",
      ">> from langchain import SQLDatabase\n",
      "\n",
      "with new imports of:\n",
      "\n",
      ">> from langchain_community.utilities import SQLDatabase\n",
      "You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>\n",
      "  from langchain.sql_database import SQLDatabase\n",
      "/home/bot/personal_proj/moneylion-ml-assessment/classes.py:7: LangChainDeprecationWarning: Importing SQLDatabase from langchain is deprecated. Please replace deprecated imports:\n",
      "\n",
      ">> from langchain import SQLDatabase\n",
      "\n",
      "with new imports of:\n",
      "\n",
      ">> from langchain_community.utilities import SQLDatabase\n",
      "You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>\n",
      "  from langchain.sql_database import SQLDatabase\n",
      "2025-01-24 12:46:49,278 - utils - INFO - Using CPU for model loading and inference.\n",
      "2025-01-24 12:46:49,278 - utils - INFO - get_device: cpu\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3298, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 622, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "sqlite3.OperationalError: unable to open database file\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/bot/personal_proj/moneylion-ml-assessment/main.py\", line 447, in <module>\n",
      "    initialize_database()\n",
      "  File \"/home/bot/personal_proj/moneylion-ml-assessment/mydatabase.py\", line 135, in initialize_database\n",
      "    sqlite_db = SQLiteDB(db_path=db_path)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/personal_proj/moneylion-ml-assessment/mydatabase.py\", line 64, in __init__\n",
      "    Base.metadata.create_all(self.engine)\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/sql/schema.py\", line 5900, in create_all\n",
      "    bind._run_ddl_visitor(\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3248, in _run_ddl_visitor\n",
      "    with self.begin() as conn:\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/contextlib.py\", line 137, in __enter__\n",
      "    return next(self.gen)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3238, in begin\n",
      "    with self.connect() as conn:\n",
      "         ^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3274, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 148, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 2439, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3298, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/bot/.pyenv/versions/3.11.5/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 622, in connect\n",
      "    return self.loaded_dbapi.connect(*cargs, **cparams)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
     ]
    }
   ],
   "source": [
    "! python main.py"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
